sensor:
  min_distance: 0.05
  max_distance: 100.0
  device_name: "Velodyne HDL-32E"
ros:
  queue_depth: 100
  velodyne_binary_snappy_topic_name: "/velodyne/binary_snappy"
  velodyne_data_packet_topic_name: "/velodyne/data_packet"
  use_binary_snappy: true
  num_data_packets: 174 # approximate number of packets per revolution (10 Hz)
  point_cloud_topic_name: "point_cloud"
  transport_type: "udp" # tcp or udp
  subscription_updater_rate: 1.0
